MVC_Database/Models/ViewModels/AssignViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Database.Models
{
    public class AssignViewModel
    {
        public List<Student> StudentList { get; set; }

        public List<Course> CourseList { get; set; }

        public List<Teacher> TeacherList { get; set; }

        public List<Assignment> AssignmentList { get; set; }
    }
}

MVC_Database/Controllers/AssignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC_Database.Models;

namespace MVC_Database.Controllers
{
    //Admin & Mods
    public class AssignController : Controller
    {
        readonly IStudentService _studentService;
        readonly ITeacherService _teacherService;
        readonly ICourseService _courseService;
        readonly IAssignmentService _assignmentService;

        public AssignController(IStudentService studentService, ITeacherService teacherService, ICourseService courseService, IAssignmentService assignmentService)
        {
            _studentService = studentService;
            _teacherService = teacherService;
            _courseService = courseService;
            _assignmentService = assignmentService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult AssignStudent()
        {
            List<Student> students = _studentService.All();
            List<Course> courses = _courseService.All();
            var model = new AssignViewModel { StudentList = students, CourseList = courses };

            return View(model);
        }

        [HttpPost]
        public IActionResult AssignStudent(int stuId, int couId)
        {
            if (stuId != 0 && couId != 0)
            {
                _studentService.Assign(stuId, couId);
            }
            return RedirectToAction("Index");
        }


        //Admin
        [HttpGet]
        public IActionResult AssignTeacher()
        {
            List<Teacher> teachers = _teacherService.All();
            List<Course> courses = _courseService.All();
            var model = new AssignViewModel { TeacherList = teachers, CourseList = courses };

            return View(model);
        }
        //Admin
        [HttpPost]
        public IActionResult AssignTeacher(int teaId, int couId)
        {
            if (teaId != 0 && couId != 0)
            {
                _teacherService.Assign(teaId, couId);
            }
            return RedirectToAction("Index");

        }



        [HttpGet]
        public IActionResult AssignAssignment()
        {
            List<Assignment> assignments = _assignmentService.All();
            List<Course> courses = _courseService.All();
            var model = new AssignViewModel { AssignmentList = assignments, CourseList = courses };

            return View(model);
        }

        [HttpPost]
        public IActionResult AssignAssignment(int assId, int couId)
        {
            if (assId != 0 && couId != 0)
            {
                _assignmentService.Assign(assId, couId);
            }
            return RedirectToAction("Index");
        }


        //[HttpGet]
        //public IActionResult CoursePartial()
        //{
        //    return PartialView("_SelectCourse", _courseService.All());
        //}
    }
}

MVC_Database/Views/Assign/AssignAssignment.cshtml
@model AssignViewModel
@{
    ViewData["Title"] = "AssignAssignment";
}

<h1>Assign Assignment</h1>
<br />

<form asp-action="AssignAssignment" asp-controller="Assign" method="post">
    <fieldset class="form-group">
        <div class="row">
            @*<legend class="col-form-label col-sm-2 pt-0"></legend>*@
            <div class="col-sm-10">
                <h4>Assignments</h4>
                @foreach (Assignment assignment in Model.AssignmentList)
                {
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="assId" id="gridAssignment @assignment.Id" value="@assignment.Id">
                        <label class="form-check-label" for="gridAssignment @assignment.Id">
                            @assignment.Title
                        </label>
                    </div>
                }
            </div>
        </div>
        <br />
        <div class="row">
            @*<legend class="col-form-label col-sm-2 pt-0">Courses</legend>*@
            <div class="col-sm-10">
                <h4>Courses</h4>
                @foreach (Course course in Model.CourseList)
                {
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="couId" id="gridCourse @course.Id" value="@course.Id">
                        <label class="form-check-label" for="gridCourse @course.Id">
                            @course.Title
                        </label>
                    </div>
                }
            </div>
        </div>
    </fieldset>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Confirm</button>
        </div>
    </div>
</form>

MVC_Database/Views/Assign/AssignStudent.cshtml
@model AssignViewModel
@{
    ViewData["Title"] = "AssignStudent";
}

<h1>Assign Student</h1>
<br />

<form asp-action="AssignStudent" asp-controller="Assign" method="post">
    <fieldset class="form-group">
        <div class="row">
            @*<legend class="col-form-label col-sm-2 pt-0"></legend>*@
            <div class="col-sm-10">
                <h4>Students</h4>
                @foreach (Student student in Model.StudentList)
                {
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="stuId" id="gridStudent @student.Id" value="@student.Id">
                        <label class="form-check-label" for="gridStudent @student.Id">
                            @student.Name
                        </label>
                    </div>
                }
            </div>
        </div>
        <br />
        <div class="row">
            @*<legend class="col-form-label col-sm-2 pt-0">Courses</legend>*@
            <div class="col-sm-10">
                <h4>Courses</h4>
                @foreach (Course course in Model.CourseList)
                {
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="couId" id="gridCourse @course.Id" value="@course.Id">
                        <label class="form-check-label" for="gridCourse @course.Id">
                            @course.Title
                        </label>
                    </div>
                }
            </div>
        </div>
    </fieldset>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Confirm</button>
        </div>
    </div>
</form>

MVC_Database/Views/Assign/AssignTeacher.cshtml
@model AssignViewModel
@{
    ViewData["Title"] = "AssignTeacher";
}

<h1>Assign Teacher</h1>
<br />

<form asp-action="AssignTeacher" asp-controller="Assign" method="post">
    <fieldset class="form-group">
        <div class="row">
            @*<legend class="col-form-label col-sm-2 pt-0"></legend>*@
            <div class="col-sm-10">
                <h4>Teacher</h4>
                @foreach (Teacher teacher in Model.TeacherList)
                {
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="teaId" id="gridTeacher @teacher.Id" value="@teacher.Id">
                        <label class="form-check-label" for="gridTeacher @teacher.Id">
                            @teacher.Name
                        </label>
                    </div>
                }
            </div>
        </div>
        <br />
        <div class="row">
            @*<legend class="col-form-label col-sm-2 pt-0">Courses</legend>*@
            <div class="col-sm-10">
                <h4>Courses</h4>
                @foreach (Course course in Model.CourseList)
                {
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="couId" id="gridCourse @course.Id" value="@course.Id">
                        <label class="form-check-label" for="gridCourse @course.Id">
                            @course.Title
                        </label>
                    </div>
                }
            </div>
        </div>
    </fieldset>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Confirm</button>
        </div>
    </div>
</form>

MVC_Database/Views/Assign/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Assign</h1>

<div class="row">
    <div class="col">
        <a class="btn btn-primary" asp-action="AssignStudent" >Assign Student</a>
    </div>
    @*Admin*@
    <div class="col">
        <a class="btn btn-primary" asp-action="AssignTeacher" >Assign Teacher</a>
    </div>
    <div class="col">
        <a class="btn btn-primary" asp-action="AssignAssignment" >Assign Assignment</a>
    </div>
</div>