MVC_Database/Models/ViewModels/CreateViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Database.Models
{
    public class CreateViewModel
    {
        public AssignmentViewModel Assignment { get; set; }

        public CourseViewModel Course { get; set; }

        public List<Course> CourseList { get; set; }

        public List<Teacher> TeacherList { get; set; }

    }
}

MVC_Database/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC_Database.Models;

namespace MVC_Database.Controllers
{
    //Admin and Mods
    public class CreateController : Controller
    {
        readonly IStudentService _studentService;
        readonly ITeacherService _teacherService;
        readonly ICourseService _courseService;
        readonly IAssignmentService _assignmentService;

        public CreateController(IStudentService studentService, ITeacherService teacherService, ICourseService courseService, IAssignmentService assignmentService)
        {
            _studentService = studentService;
            _teacherService = teacherService;
            _courseService = courseService;
            _assignmentService = assignmentService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateStudent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateStudent(StudentViewModel studentViewModel)
        {
            if (ModelState.IsValid)
            {
                _studentService.Create(studentViewModel);
                return RedirectToAction("Index");
            }

            return View(studentViewModel);
        }

        //Admin
        [HttpGet]
        public IActionResult CreateTeacher()
        {
            return View();
        }
        //Admin
        [HttpPost]
        public IActionResult CreateTeacher(TeacherViewModel teacherViewModel)
        {
            if (ModelState.IsValid)
            {
                _teacherService.Create(teacherViewModel);
                return RedirectToAction("Index");
            }

            return View(teacherViewModel);
        }

        //Admin
        [HttpGet]
        public IActionResult CreateCourse()
        {
            //return View(_teacherService.All());
            //CourseViewModel course = new CourseViewModel();
            //List<Teacher> teachers = _teacherService.All();
            //var model = new CreateViewModel { TeacherList = teachers, Course = course };

            return View();
        }
        //Admin
        [HttpPost]
        public IActionResult CreateCourse(CourseViewModel courseViewModel)
        {
            if (ModelState.IsValid)
            {
                //courseViewModel.Teacher = _teacherService.Find(1);

                _courseService.Create(courseViewModel);
                //return RedirectToAction("Index");
                return RedirectToAction("AssignTeacher", "Assign");
            }

            return View(courseViewModel);
        }

        //[HttpPost]
        //public IActionResult SelectTeacher(CourseViewModel courseViewModel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        List<Teacher> teachers = _teacherService.All();
        //        var model = new CreateViewModel { TeacherList = teachers, Course = courseViewModel };
        //        return View(model);
        //    }
        //    return View(courseViewModel);
        //}



        [HttpGet]
        public IActionResult CreateAssignment()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateAssignment(AssignmentViewModel assignmentViewModel)
        {
            if (ModelState.IsValid)
            {
                //assignmentViewModel.Course = _courseService.Find(2);

                _assignmentService.Create(assignmentViewModel);
                return RedirectToAction("AssignAssignment", "Assign");
            }

            return View(assignmentViewModel);
        }
    }
}

MVC_Database/Views/Create/CreateAssignment.cshtml
@model AssignmentViewModel
@{
    ViewData["Title"] = "CreateAssignment";
}

<h1>Create Assignment</h1>

<form asp-action="CreateAssignment" asp-controller="Create" method="post">

    <label asp-for="Title"></label>
    <input asp-for="Title" />
    <span asp-validation-for="Title"></span>
    <br />

    <label asp-for="Description"></label>
    <input asp-for="Description" />
    <span asp-validation-for="Description"></span>
    <br />

    <input type="submit" value="Create" />
</form>

MVC_Database/Views/Create/CreateCourse.cshtml
@*@model CreateViewModel*@
@model CourseViewModel
@{
    ViewData["Title"] = "CreateCourse";
}

<h1>Create Course</h1>

<form asp-action="CreateCourse" asp-controller="Create" method="post">

    <label asp-for="Title"></label>
    <input asp-for="Title" />
    <span asp-validation-for="Title"></span>
    <br />

    <label asp-for="Description"></label>
    <input asp-for="Description" />
    <span asp-validation-for="Description"></span>
    <br />

    <input type="submit" value="Create" />
</form>

MVC_Database/Views/Create/CreateStudent.cshtml
@model StudentViewModel
@{
    ViewData["Title"] = "CreateStudent";
}

<h1>Create Student</h1>

<form asp-action="CreateStudent" asp-controller="Create" method="post">

    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span>
    <br />

    <label asp-for="Email"></label>
    <input asp-for="Email" />
    <span asp-validation-for="Email"></span>
    <br />

    <input type="submit" value="Create" />
</form>

MVC_Database/Views/Create/CreateTeacher.cshtml
@model TeacherViewModel
@{
    ViewData["Title"] = "CreateTeacher";
}

<h1>Create Teacher</h1>

<form asp-action="CreateTeacher" asp-controller="Create" method="post">

    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <span asp-validation-for="Name"></span>
    <br />

    <label asp-for="Email"></label>
    <input asp-for="Email" />
    <span asp-validation-for="Email"></span>
    <br />

    <label asp-for="Office"></label>
    <input asp-for="Office" />
    <span asp-validation-for="Office"></span>
    <br />

    <input type="submit" value="Create" />
</form>

MVC_Database/Views/Create/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Create</h1>

<div class="row">
    <div class="col">
        <a class="btn btn-primary" asp-action="CreateStudent">Create Student</a>
    </div>
    <div class="col">
        <a class="btn btn-primary" asp-action="CreateAssignment">Create Assignment</a>
    </div>
</div>
<br />
    @*Admin*@
<div class="row">
    <div class="col">
        <a class="btn btn-primary" asp-action="CreateCourse">Create Course</a>
    </div>
    <div class="col">
        <a class="btn btn-primary" asp-action="CreateTeacher">Create Teacher</a>
    </div>
</div>

MVC_Database/Views/Create/SelectTeacher.cshtml
@model CreateViewModel
@{
    ViewData["Title"] = "SelectTeacher";
}

<h1>Select Teacher</h1>

<form asp-action="SelectTeacher" asp-controller="Create" method="post">

    @foreach (Teacher teacher in Model.TeacherList)
    {
        <div class="form-check">
            <input class="form-check-input" type="radio" name="teaId" id="gridTeacher @teacher.Id" value="@teacher.Id">
            <label class="form-check-label" for="gridTeacher @teacher.Id">
                @teacher.Name
            </label>
        </div>
    }

    <input type="hidden" value="@Model.Course." />

    <input type="submit" value="Create" />
</form>